"""URLs de famílias Certideal (verificadas HTTP 200)."""

from __future__ import annotations

CERTIDEAL_URLS: dict[str, list[dict[str, str]]] = {
    "iphones": [
        {"model": "iPhone 11 Pro Max", "url": "https://www.certideal.pt/iphone-11-pro-max-recondicionado-248"},
        {"model": "iPhone 11 Pro", "url": "https://www.certideal.pt/iphone-11-pro-recondicionado-245"},
        {"model": "iPhone 11", "url": "https://www.certideal.pt/iphone-11-recondicionado-213"},
        {"model": "iPhone 12 Mini", "url": "https://www.certideal.pt/iphone-12-mini-264"},
        {"model": "iPhone 12 Pro", "url": "https://www.certideal.pt/iphone-12-pro-266"},
        {"model": "iPhone 12 Pro Max", "url": "https://www.certideal.pt/iphone-12-pro-max-276"},
        {"model": "iPhone 12", "url": "https://www.certideal.pt/iphone-12-recondicionado-261"},
        {"model": "iPhone 13", "url": "https://www.certideal.pt/iphone-13-288"},
        {"model": "iPhone 13 Mini", "url": "https://www.certideal.pt/iphone-13-mini-289"},
        {"model": "iPhone 13 Pro", "url": "https://www.certideal.pt/iphone-13-pro-301"},
        {"model": "iPhone 13 Pro Max", "url": "https://www.certideal.pt/iphone-13-pro-max-302"},
        {"model": "iPhone 14", "url": "https://www.certideal.pt/iphone-14-312"},
        {"model": "iPhone 14 Plus", "url": "https://www.certideal.pt/iphone-14-plus-386"},
        {"model": "iPhone 14 Pro", "url": "https://www.certideal.pt/iphone-14-pro-410"},
        {"model": "iPhone 14 Pro Max", "url": "https://www.certideal.pt/iphone-14-pro-max-326"},
        {"model": "iPhone 15", "url": "https://www.certideal.pt/iphone-15-372"},
        {"model": "iPhone 15 Plus", "url": "https://www.certideal.pt/iphone-15-plus-415"},
        {"model": "iPhone 15 Pro", "url": "https://www.certideal.pt/iphone-15-pro-416"},
        {"model": "iPhone 15 Pro Max", "url": "https://www.certideal.pt/iphone-15-pro-max-409"},
        {"model": "iPhone 16", "url": "https://www.certideal.pt/iphone-16-545"},
        {"model": "iPhone 16 Plus", "url": "https://www.certideal.pt/iphone-16-plus-546"},
        {"model": "iPhone 16 Pro", "url": "https://www.certideal.pt/iphone-16-pro-544"},
        {"model": "iPhone 16 Pro Max", "url": "https://www.certideal.pt/iphone-16-pro-max-543"},
        {"model": "iPhone 16e", "url": "https://www.certideal.pt/iphone-16e-578"},
        {"model": "iPhone 17 Series", "url": "https://www.certideal.pt/iphone-17-series-639"},
        {"model": "iPhone 7 Plus", "url": "https://www.certideal.pt/iphone-7-plus-169"},
        {"model": "iPhone 7", "url": "https://www.certideal.pt/iphone-7-recondicionado-164"},
        {"model": "iPhone 8 Plus", "url": "https://www.certideal.pt/iphone-8-plus-recondicionado-175"},
        {"model": "iPhone 8", "url": "https://www.certideal.pt/iphone-8-recondicionado-174"},
        {"model": "iPhone Air", "url": "https://www.certideal.pt/iphone-air-643"},
        {"model": "iPhone SE (2020)", "url": "https://www.certideal.pt/iphone-se-2-2020-249"},
        {"model": "iPhone SE (2022)", "url": "https://www.certideal.pt/iphone-se-3-2022-392"},
        {"model": "iPhone X", "url": "https://www.certideal.pt/iphone-x-recondicionado-182"},
        {"model": "iPhone XR", "url": "https://www.certideal.pt/iphone-xr-recondicionado-205"},
        {"model": "iPhone XS Max", "url": "https://www.certideal.pt/iphone-xs-max-recondicionado-208"},
        {"model": "iPhone XS", "url": "https://www.certideal.pt/iphone-xs-recondicionado-207"},
    ],
    "ipads": [
        {"model": "iPad 10.2 WiFi 5G", "url": "https://www.certideal.pt/ipad-10-wifi-5g-369"},
        {"model": "iPad 11 WiFi", "url": "https://www.certideal.pt/ipad-11-wifi-580"},
        {"model": "iPad", "url": "https://www.certideal.pt/ipad-349"},
        {"model": "iPad 9 WiFi 5G", "url": "https://www.certideal.pt/ipad-9-wifi-5g-316"},
        {"model": "iPad Air", "url": "https://www.certideal.pt/ipad-air-348"},
        {"model": "iPad Air 6 WiFi", "url": "https://www.certideal.pt/ipad-air-6-wifi-649"},
        {"model": "iPad Mini", "url": "https://www.certideal.pt/ipad-mini-350"},
        {"model": "iPad Mini 6 WiFi", "url": "https://www.certideal.pt/ipad-mini-6-wifi-365"},
        {"model": "iPad Pro 2021 WiFi", "url": "https://www.certideal.pt/ipad-pro-129-2021-wifi-339"},
        {"model": "iPad Pro 2021 WiFi 5G", "url": "https://www.certideal.pt/ipad-pro-129-2021-wifi-5g-340"},
        {"model": "iPad Pro", "url": "https://www.certideal.pt/ipad-pro-347"},
    ],
    "samsung_phones": [
        {"model": "Samsung Galaxy A03 461", "url": "https://www.certideal.pt/samsung-galaxy-a03-461"},
        {"model": "Samsung Galaxy A05 685", "url": "https://www.certideal.pt/samsung-galaxy-a05-685"},
        {"model": "Samsung Galaxy A05S 460", "url": "https://www.certideal.pt/samsung-galaxy-a05s-460"},
        {"model": "Samsung Galaxy A06 682", "url": "https://www.certideal.pt/samsung-galaxy-a06-682"},
        {"model": "Samsung Galaxy A10 654", "url": "https://www.certideal.pt/samsung-galaxy-a10-654"},
        {"model": "Samsung Galaxy A12 475", "url": "https://www.certideal.pt/samsung-galaxy-a12-475"},
        {"model": "Samsung Galaxy A13 645", "url": "https://www.certideal.pt/samsung-galaxy-a13-645"},
        {"model": "Samsung Galaxy A14 406", "url": "https://www.certideal.pt/samsung-galaxy-a14-406"},
        {"model": "Samsung Galaxy A15 459", "url": "https://www.certideal.pt/samsung-galaxy-a15-459"},
        {"model": "Samsung Galaxy A16 644", "url": "https://www.certideal.pt/samsung-galaxy-a16-644"},
        {"model": "Samsung Galaxy A17 679", "url": "https://www.certideal.pt/samsung-galaxy-a17-679"},
        {"model": "Samsung Galaxy A23 474", "url": "https://www.certideal.pt/samsung-galaxy-a23-474"},
        {"model": "Samsung Galaxy A24 694", "url": "https://www.certideal.pt/samsung-galaxy-a24-694"},
        {"model": "Samsung Galaxy A33 677", "url": "https://www.certideal.pt/samsung-galaxy-a33-677"},
        {"model": "Samsung Galaxy A36 681", "url": "https://www.certideal.pt/samsung-galaxy-a36-681"},
        {"model": "Samsung Galaxy A41 696", "url": "https://www.certideal.pt/samsung-galaxy-a41-696"},
        {"model": "Samsung Galaxy A5 697", "url": "https://www.certideal.pt/samsung-galaxy-a5-697"},
        {"model": "Samsung Galaxy A51 653", "url": "https://www.certideal.pt/samsung-galaxy-a51-653"},
        {"model": "Samsung Galaxy A52S 674", "url": "https://www.certideal.pt/samsung-galaxy-a52s-674"},
        {"model": "Samsung Galaxy A6 692", "url": "https://www.certideal.pt/samsung-galaxy-a6-692"},
        {"model": "Samsung Galaxy A71 691", "url": "https://www.certideal.pt/samsung-galaxy-a71-691"},
        {"model": "Samsung Galaxy A71 698", "url": "https://www.certideal.pt/samsung-galaxy-a71-698"},
        {"model": "Samsung Galaxy A72 680", "url": "https://www.certideal.pt/samsung-galaxy-a72-680"},
        {"model": "Samsung Galaxy Note 10 Lite 684", "url": "https://www.certideal.pt/samsung-galaxy-note-10-lite-684"},
        {"model": "Samsung Galaxy Note 20 Ultra 683", "url": "https://www.certideal.pt/samsung-galaxy-note-20-ultra-683"},
        {"model": "Samsung Galaxy S10 210", "url": "https://www.certideal.pt/samsung-galaxy-s10-210"},
        {"model": "Samsung Galaxy S10 Lite 693", "url": "https://www.certideal.pt/samsung-galaxy-s10-lite-693"},
        {"model": "Samsung Galaxy S10 Plus 211", "url": "https://www.certideal.pt/samsung-galaxy-s10-plus-211"},
        {"model": "Samsung Galaxy S10E 209", "url": "https://www.certideal.pt/samsung-galaxy-s10e-209"},
        {"model": "Samsung Galaxy S20 325", "url": "https://www.certideal.pt/samsung-galaxy-s20-325"},
        {"model": "Samsung Galaxy S20 FE 413", "url": "https://www.certideal.pt/samsung-galaxy-s20-fe-413"},
        {"model": "Samsung Galaxy S20 Plus 402", "url": "https://www.certideal.pt/samsung-galaxy-s20-plus-402"},
        {"model": "Samsung Galaxy S21 391", "url": "https://www.certideal.pt/samsung-galaxy-s21-391"},
        {"model": "Samsung Galaxy S21 FE 468", "url": "https://www.certideal.pt/samsung-galaxy-s21-fe-468"},
        {"model": "Samsung Galaxy S21 Plus 403", "url": "https://www.certideal.pt/samsung-galaxy-s21-plus-403"},
        {"model": "Samsung Galaxy S21 Ultra 549", "url": "https://www.certideal.pt/samsung-galaxy-s21-ultra-549"},
        {"model": "Samsung Galaxy S22 405", "url": "https://www.certideal.pt/samsung-galaxy-s22-405"},
        {"model": "Samsung Galaxy S22 Plus 466", "url": "https://www.certideal.pt/samsung-galaxy-s22-plus-466"},
        {"model": "Samsung Galaxy S22 Ultra 467", "url": "https://www.certideal.pt/samsung-galaxy-s22-ultra-467"},
        {"model": "Samsung Galaxy S23 FE 457", "url": "https://www.certideal.pt/samsung-galaxy-s23-fe-457"},
        {"model": "Samsung Galaxy S23 Plus 637", "url": "https://www.certideal.pt/samsung-galaxy-s23-plus-637"},
        {"model": "Samsung Galaxy S23 Ultra 464", "url": "https://www.certideal.pt/samsung-galaxy-s23-ultra-464"},
        {"model": "Samsung Galaxy S23Galaxy S23 465", "url": "https://www.certideal.pt/samsung-galaxy-s23samsung-galaxy-s23-465"},
        {"model": "Samsung Galaxy S24 455", "url": "https://www.certideal.pt/samsung-galaxy-s24-455"},
        {"model": "Samsung Galaxy S24 Plus 456", "url": "https://www.certideal.pt/samsung-galaxy-s24-plus-456"},
        {"model": "Samsung Galaxy S24 Ultra 671", "url": "https://www.certideal.pt/samsung-galaxy-s24-ultra-671"},
        {"model": "Samsung Galaxy S25 648", "url": "https://www.certideal.pt/samsung-galaxy-s25-648"},
        {"model": "Samsung Galaxy S25 FE 655", "url": "https://www.certideal.pt/samsung-galaxy-s25-fe-655"},
        {"model": "Samsung Galaxy S25 Plus 675", "url": "https://www.certideal.pt/samsung-galaxy-s25-plus-675"},
        {"model": "Samsung Galaxy S25 Ultra 647", "url": "https://www.certideal.pt/samsung-galaxy-s25-ultra-647"},
        {"model": "Samsung Galaxy Z Flip6 670", "url": "https://www.certideal.pt/samsung-galaxy-z-flip6-670"},
        {"model": "Samsung Galaxy Z Flip7 673", "url": "https://www.certideal.pt/samsung-galaxy-z-flip7-673"},
        {"model": "Samsung Galaxy Z Fold4 686", "url": "https://www.certideal.pt/samsung-galaxy-z-fold4-686"},
        {"model": "Samsung Galaxy Z Fold6 678", "url": "https://www.certideal.pt/samsung-galaxy-z-fold6-678"},
        {"model": "Samsung Galaxy Z Fold7 700", "url": "https://www.certideal.pt/samsung-galaxy-z-fold7-700"},
    ],
}
